# Site
name: 'Abhishek Bamotra'
description: 'A Robot Lover'
logo: 'assets/images/abhiblogo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'abhib'
email: 'abamotra1707@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Abhishek
      site:           https://www.tipsindeed.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I'm Abhishek Bamotra, a robotics enthusiast!"
      email:          abamotra1707@gmail.com
      twitter:        https://twitter.com/abhibamotra
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Abhishek
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
